name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - name: Installing
        run: npm install
      - name: Testing
        run: npm test
        env:
          CI: true
